data: DIR
model: resnet101
pretrained: false
initial-checkpoint: ''
resume: ''
no-resume-opt: false
num-classes: 1000
gp: null
img-size: null
crop-pct: null
mean: null
std: null
interpolation: ''
batch-size: 32
validation-batch-size-multiplier: 1
opt: sgd
opt-eps: null
opt-betas: null
momentum: 0.9
weight-decay: 0.0001
clip-grad: null
sched: step
lr: 0.01
lr-noise: null
lr-noise-pct: 0.67
lr-noise-std: 1.0
lr-cycle-mul: 1.0
lr-cycle-limit: 1
warmup-lr: 0.0001
min-lr: 1e-5
epochs: 200
start-epoch: null
decay-epochs: 30
warmup-epochs: 3
cooldown-epochs: 10
patience-epochs: 10
decay-rate: 0.1
no-aug: false
repeated-aug: false
scale: [0.08, 1.0]
ratio: [0.75, 1.33]
hflip: 0.5
vflip: 0.0
color-jitter: 0.4
aa: null
aug-splits: 0
jsd: false
reprob: 0.0
remode: const
recount: 1
resplit: false
mixup: 0.0
cutmix: 0.0
cutmix-minmax: null
mixup-prob: 1.0
mixup-switch-prob: 0.5
mixup-mode: batch
mixup-off-epoch: 0
smoothing: 0.1
train-interpolation: random
drop: 0.0
drop-connect: null
drop-path: null
drop-block: null
bn-tf: false
bn-momentum: null
bn-eps: null
sync-bn: false
dist-bn: ''
split-bn: false
model-ema: false
model-ema-force-cpu: false
model-ema-decay: 0.9998
seed: 42
log-interval: 50
recovery-interval: 0
workers: 4
num-gpu: 1
save-images: false
amp: false
apex-amp: false
native-amp: false
channels-last: false
pin-mem: false
no-prefetcher: false
output: ''
eval-metric: top1
tta: 0
local_rank: 0
use-multi-epochs-loader: false
init_method: env://
train_url: null
attn_ratio: 1.0
pretrain_path: null
evaluate: false
